'use strict';
let currentAudio=null,audioToken=0,lastAutoWord='';
function reviewDate(id){const s=S.senses[id];if(!s?.practice)return s?.selfMark?'已保留辅助标记；完成一次填写练习后安排复习。':'尚未开始填写练习。';if(!Number.isFinite(s.due)||s.due<946684800000)return '现在可复习';if(s.due<=Date.now())return '已到复习时间';return '下次复习：'+new Date(s.due).toLocaleString('zh-CN');}
function soundButton(w){return `<span class="pronunciation"><button type="button" data-audio="${E(w.id)}" aria-label="播放 ${E(w.lemma)} 的德语发音">▶ 再听一遍</button><span class="small muted" data-audio-status="${E(w.id)}">${w.audio?'德语真人录音 · 需联网':'系统德语朗读'}</span>${w.audio?`<a class="small text-link" href="${E(w.audio.source)}" target="_blank" rel="noopener">录音来源与许可 ↗</a>`:''}</span>`;}
function audioStatus(id,message){document.querySelectorAll('[data-audio-status]').forEach(el=>{if(el.dataset.audioStatus===id)el.textContent=message;});}
function stopAudio(){audioToken++;if(currentAudio){currentAudio.pause();currentAudio=null;}window.speechSynthesis?.cancel();}
async function pronounce(id,automatic=false){const w=C.words[id];if(!w)return;stopAudio();const token=audioToken;
 if(w.audio){currentAudio=new Audio(w.audio.url);currentAudio.preload='none';currentAudio.onended=()=>audioStatus(id,'播放完成 · 点击可重复播放');try{await currentAudio.play();if(token===audioToken)audioStatus(id,'正在播放德语录音…');return;}catch(e){if(token!==audioToken)return;if(e.name==='NotAllowedError'){audioStatus(id,'点击按钮播放发音');return;}audioStatus(id,'录音暂不可用，尝试系统德语朗读');}}
 if(!window.speechSynthesis){audioStatus(id,'当前浏览器无法朗读，可打开录音来源');return;}
 const voices=speechSynthesis.getVoices(),voice=voices.find(v=>v.lang==='de-DE')||voices.find(v=>v.lang.startsWith('de'));
 if(!voice){audioStatus(id,'未发现德语语音；请在设备语音设置中添加德语');return;}
 const utterance=new SpeechSynthesisUtterance(w.lemma);utterance.lang=voice.lang;utterance.voice=voice;utterance.rate=.85;
 utterance.onstart=()=>audioStatus(id,'正在播放系统德语朗读…');utterance.onend=()=>audioStatus(id,'系统德语朗读 · 点击可重复播放');utterance.onerror=()=>audioStatus(id,automatic?'点击按钮播放发音':'系统语音暂不可用');speechSynthesis.speak(utterance);
}
function autoPronounce(){const raw=location.hash.slice(1).split('?')[0];let id='';if(raw.startsWith('/word/'))id=decodeURIComponent(raw.slice(6));else if(raw==='/flash'&&flash?.cards?.[flash.index]?.dir==='de-zh')id=C.senses[flash.cards[flash.index].id]?.word.id||'';const key=raw+':'+id+':'+(raw==='/flash'?flash?.index:'');if(id&&key!==lastAutoWord){lastAutoWord=key;pronounce(id,true);}else if(!id){lastAutoWord='';stopAudio();}}
function noteEditor(id){return `<label class="note-editor">我的联想 / 译法备注<textarea data-note="${E(id)}" maxlength="2000" placeholder="写下你自己的画面、关联词或译法…">${E(S.senses[id]?.note||'')}</textarea><span class="small muted">输入后自动保存在此设备；备注不改变熟练度。</span></label>`;}
function associationMap(w,s){const nodes=(s.associations||w.associations||[]).slice(0,6),caption=w.associationTopic||'搭配联想';if(!nodes.length)return `<details class="association"><summary>搭配联想 · ${E(w.lemma)}</summary><p>本词的搭配图仍在补充，可先查看 Duden 的典型搭配。</p>${external('https://www.duden.de/suchen/dudenonline/'+enc(w.lemma),'在 Duden 查询典型搭配 ↗')}</details>`;const pos=nodes.map((_,i)=>{const a=-Math.PI/2+i*2*Math.PI/nodes.length;return [50+36*Math.cos(a),50+36*Math.sin(a)];});return `<details class="association" open><summary>${caption==='常用搭配'?'典型搭配 · 圆圈联想':'联想记忆 · '+E(caption)}</summary><div class="radial-map" aria-label="${E(w.lemma)} 的${E(caption)}"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${pos.map(([x,y])=>`<line x1="50" y1="50" x2="${x}" y2="${y}"/>`).join('')}</svg><div class="radial-center"><b lang="de">${E(w.lemma)}</b><small>${E(s.zh.split('；')[0].slice(0,24))}</small></div>${nodes.map((n,i)=>{const target=n.word||Object.keys(C.words).find(id=>n.label.split(' ').includes(id)&&id!==w.id);return `<button class="radial-node" style="left:${pos[i][0]}%;top:${pos[i][1]}%" ${target?`data-lookup="${E(target)}"`:''} aria-label="${E(n.label+'：'+n.zh)}"><b lang="de">${E(n.label)}</b><small>${E(n.zh)}</small></button>`;}).join('')}</div><p class="small muted">${caption==='常用搭配'?'搭配按学习用途整理，不表示语料频次排名。':'同场景或词族关联，不等同于高频共现或近义关系。'} ${w.id==='Kopf'?`<a class="text-link" href="https://www.duden.de/rechtschreibung/Kopf#typische-verbindungen" target="_blank" rel="noopener">参考 Duden 典型搭配 ↗</a>`:''}</p></details>`;}
function advanceFlash(){if(!flash)return;flash.index++;flash.shown=false;flash.hinted=false;flash.result=null;flash.answer='';render();document.querySelector('#recall-answer')?.focus();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.audio){pronounce(b.dataset.audio);return;}if(b.dataset.flashNext){advanceFlash();return;}});
function pronounceText(text){if(!text||!window.speechSynthesis)return;window.speechSynthesis.cancel();const voices=speechSynthesis.getVoices(),voice=voices.find(v=>v.lang==='de-DE')||voices.find(v=>v.lang.startsWith('de'));if(!voice){toast('请在设备语音设置中添加德语语音');return;}const u=new SpeechSynthesisUtterance(text);u.lang=voice.lang;u.voice=voice;u.rate=.82;speechSynthesis.speak(u);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-speak]');if(!b)return;e.preventDefault();e.stopPropagation();pronounceText(b.dataset.speak);});
let noteTimer;document.addEventListener('input',e=>{if(e.target.dataset.note){const id=e.target.dataset.note;if(!C.senses[id])return;S.senses[id]??={};S.senses[id].note=e.target.value.slice(0,2000);clearTimeout(noteTimer);noteTimer=setTimeout(save,350);}if(e.target.id==='recall-answer'&&flash)flash.answer=e.target.value;});
document.addEventListener('submit',e=>{if(e.target.id==='flash-setup'){e.preventDefault();const f=new FormData(e.target),ls=f.getAll('levels').filter(l=>levels.includes(l));if(!ls.length){toast('请至少选择一个阶段的词库。');return;}S.settings.wordLevels=ls;S.settings.wordCount=Number(f.get('count'));S.settings.wordMode=f.get('mode');save();flash=null;location.hash='/flash?start=1';}
 if(e.target.id==='review-settings'){e.preventDefault();C.setReviewHour(S,Number(new FormData(e.target).get('hour')));save();render();toast('已保存每日复习刷新时间');}
 if(e.target.id==='recall-form'){e.preventDefault();if(!flash||flash.result)return;const answer=String(new FormData(e.target).get('answer')||'');if(!answer.trim()){toast('先写下你的答案；也可点击提示。');return;}const card=flash.cards[flash.index];flash.answer=answer;flash.result=C.practice(S,card.id,card.dir,answer,flash.hinted);if(flash.result.ok)flash.correct++;save();render();}});
window.addEventListener('pagehide',stopAudio);
